version: 2
jobs: 
  build: 
    docker: 
      # specify the version you desire here
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps: 
      - checkout

      # Download and cache dependencies
      - restore_cache: 
          keys: 
          - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache: 
          paths: 
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          command: git push https://heroku:f1d640b0-8611-431f-af9a-214b98624962@git.heroku.com/ops200-delivery.git main

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build